export const SIGN_IN_GOOGLE ='SIGN_IN_GOOGLE';
export const SIGN_OUT_GOOGLE ='SIGN_OUT_GOOGLE';
export const CREATE_USER_EMAIL_PASSWORD ='CREATE_USER_EMAIL_PASSWORD';
export const ADD_ERROR='ADD_ERROR';
export const SET_USER ='SET_USER';
export const SIGN_IN_EMAIL ='SIGN_IN_EMAIL';
export const SIGN_OUT_EMAIL ='SIGN_OUT_EMAIL';

